name: Test Self-hosted Runner

on:
  push:
    branches:
      - main

jobs:
  test-runner:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Hello World
        run: echo "Hello from the GitHub Actions runner!"

      - name: Print Current Directory
        run: pwd

      - name: List Files
        run: ls -la
