name: Test Multi-Job

on:
  push:
    branches: [ main ]

jobs:
  create_file:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: abc
    steps:
      - name: Create file
        run: |
          echo "This file was created in Job 2." > shared-file.txt

      - name: Upload file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: shared-artifact
          path: shared-file.txt

  read_file:
    needs: create_file
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: shared-artifact

      - name: Show file content
        run: |
          echo "Reading content from shared-file.txt:"
          cat shared-file.txt
