name: Test Multi-Job

on:
  push:
    branches: main

jobs:
  task1:
    runs-on: ubuntu-latest
    steps:
      - name: Create file
        run: |
          echo "This file was created in Job 6." > shared-file-1.txt

      - uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: my-artifact
          path: shared-file-1.txt
  task2:
    runs-on: ubuntu-latest
    needs: task1
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact

      - name: read the file
        run: cat shared-file-1.txt
